# Generated by Django 5.2.1 on 2025-05-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_alter_bank_options_alter_branch_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bank',
            table='banks',
        ),
        migrations.AlterModelTable(
            name='branch',
            table='branches',
        ),
    ]
